FROM python:3.13.11-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

WORKDIR /code

COPY pyproject.toml .python-version uv.lock ./
COPY pipeline.py .

RUN uv sync --locked

ENTRYPOINT ["uv", "run", "pipeline.py"]